'From Cuis 4.2 of 25 July 2013 [latest update: #1808] on 24 August 2013 at 10:28:07.655576 am'!
'Description Please enter a description for this package'!
!provides: 'Cuis-Network-Installer' 1 0!
!requires: 'Cuis-System-Hashing' 1 0 nil!
!requires: 'Cuis-CompatibilityWithOtherSmalltalks' 1 0 nil!
!requires: 'Cuis-Network-Url' 1 0 nil!
!requires: 'Cuis-Network-MIME' 1 0 nil!
!requires: 'Cuis-Network-UUID' 1 0 nil!
!requires: 'Cuis-NetworkTests-UUID' 1 0 nil!
!requires: 'Cuis-Network-RFC822' 1 0 nil!
!requires: 'Cuis-Settings-Network' 1 0 nil!
!requires: 'Cuis-NetworkTests-Protocols' 1 0 nil!
!requires: 'Cuis-NetworkTests-RFC822' 1 0 nil!
!requires: 'Cuis-Network-Protocols' 1 0 nil!
!classDefinition: #CuisNetworkInstaller category: #'Cuis-Network-Installer'!
Object variableByteSubclass: #CuisNetworkInstaller
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Cuis-Network-Installer'!
!classDefinition: 'CuisNetworkInstaller class' category: #'Cuis-Network-Installer'!
CuisNetworkInstaller class
	instanceVariableNames: ''!

